package com.froydinger.breeze.data

import android.content.Context
import android.net.Uri
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.io.DataInputStream
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.CipherInputStream
import javax.crypto.CipherOutputStream
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/** Device-only encrypted storage for chat photos. The image bytes are never cloud-synced. */
class LocalChatImageStore(context: Context) {
    private val appContext = context.applicationContext
    private val resolver = appContext.contentResolver
    private val directory = File(appContext.noBackupFilesDir, "chat-image-attachments")

    /** Copies the picker URI once, so previews and sending no longer depend on its temporary grant. */
    @Throws(IOException::class)
    fun copySelectedPhoto(uri: Uri): String {
        val id = java.util.UUID.randomUUID().toString()
        val file = imageFile(id)
        if (!directory.exists() && !directory.mkdirs() && !directory.isDirectory) {
            throw IOException("Breeze couldn't prepare private photo storage.")
        }
        try {
            val source = resolver.openInputStream(uri)
                ?: throw IOException("Breeze couldn't open that photo. Choose it again.")
            var copied = 0L
            source.use { input ->
                // Android Keystore requires GCM encryption IVs to be generated by
                // the provider when randomized encryption is enabled. Supplying a
                // SecureRandom nonce here makes Cipher.init fail on real devices.
                val cipher = Cipher.getInstance(TRANSFORMATION)
                cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
                val nonce = cipher.iv?.takeIf { it.size == GCM_NONCE_BYTES }
                    ?: throw IOException("Breeze couldn't prepare secure photo storage.")
                cipher.updateAAD(aad(id))
                FileOutputStream(file).use { raw ->
                    raw.write(MAGIC)
                    raw.write(nonce)
                    CipherOutputStream(raw, cipher).use { encrypted ->
                        val buffer = ByteArray(COPY_BUFFER_BYTES)
                        while (true) {
                            val count = input.read(buffer)
                            if (count < 0) break
                            copied += count
                            if (copied > MAX_SOURCE_BYTES) {
                                throw IOException("That photo is too large to attach. Choose a smaller one.")
                            }
                            encrypted.write(buffer, 0, count)
                        }
                    }
                }
            }
            if (copied == 0L) throw IOException("Breeze couldn't read that photo. Choose it again.")
            return imageUri(id)
        } catch (error: Exception) {
            file.delete()
            if (error is IOException) throw error
            throw IOException("Breeze couldn't save that photo for chat. Choose it again.", error)
        }
    }

    /** Opens an app-owned attachment as a decrypted stream; legacy picker URIs still use Android's resolver. */
    @Throws(IOException::class)
    fun open(uriText: String): InputStream? {
        val uri = Uri.parse(uriText)
        if (uri.scheme != URI_SCHEME) return resolver.openInputStream(uri)
        val id = uri.authority?.takeIf(UUID_PATTERN::matches) ?: throw IOException("This saved photo is unavailable.")
        val raw = FileInputStream(imageFile(id))
        try {
            val input = DataInputStream(raw)
            val magic = ByteArray(MAGIC.size)
            input.readFully(magic)
            if (!magic.contentEquals(MAGIC)) throw IOException("This saved photo is unavailable.")
            val nonce = ByteArray(GCM_NONCE_BYTES)
            input.readFully(nonce)
            val cipher = Cipher.getInstance(TRANSFORMATION).apply {
                init(Cipher.DECRYPT_MODE, getOrCreateKey(), GCMParameterSpec(GCM_TAG_BITS, nonce))
                updateAAD(aad(id))
            }
            return CipherInputStream(input, cipher)
        } catch (error: Exception) {
            raw.close()
            if (error is IOException) throw error
            throw IOException("This saved photo couldn't be opened.", error)
        }
    }

    fun delete(uriText: String) {
        ownedId(uriText)?.let { imageFile(it).delete() }
    }

    /** Removes abandoned pending uploads and files belonging to deleted chats. */
    fun removeUnreferenced(referencedUris: Set<String>) {
        val retainedIds = referencedUris.mapNotNull(::ownedId).toSet()
        directory.listFiles()?.forEach { file ->
            val id = file.name.removeSuffix(FILE_SUFFIX)
            if (id !in retainedIds) file.delete()
        }
    }

    private fun imageUri(id: String): String = Uri.Builder().scheme(URI_SCHEME).authority(id).build().toString()

    private fun ownedId(uriText: String): String? = Uri.parse(uriText).takeIf { it.scheme == URI_SCHEME }
        ?.authority?.takeIf(UUID_PATTERN::matches)

    private fun imageFile(id: String) = File(directory, "$id$FILE_SUFFIX")
    private fun aad(id: String) = "$URI_SCHEME:$id".toByteArray(Charsets.UTF_8)

    private fun getOrCreateKey(): SecretKey {
        val store = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (store.getKey(KEY_ALIAS, null) as? SecretKey)?.let { return it }
        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setKeySize(256)
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setRandomizedEncryptionRequired(true)
                .build(),
        )
        return generator.generateKey()
    }

    private companion object {
        const val URI_SCHEME = "breeze-chat-image"
        const val FILE_SUFFIX = ".bci"
        const val KEY_ALIAS = "com.froydinger.breeze.chat.images.v1"
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val GCM_NONCE_BYTES = 12
        const val GCM_TAG_BITS = 128
        const val COPY_BUFFER_BYTES = 32 * 1024
        const val MAX_SOURCE_BYTES = 50L * 1024L * 1024L
        val MAGIC = "BREEZEI1".toByteArray(Charsets.US_ASCII)
        val UUID_PATTERN = Regex("[0-9a-fA-F-]{36}")
    }
}
